### ISSUE TITLE
Problem Statements.

### ISSUE THREAD

**Issue by MegaCha0s** [marioyc/Online-Judge-Solutions#10]
Hello, where can I find the problem statements for TJU. I tried finding TJU Online Judge everywhere but could not find it.

**Comment by timmyjose** [comment]
TJU has been down for quite some time now. I think it is permanently down, in fact. If you simply wish to get access to the problem statements themselves, you could use something like the Wayback Machine - http://web.archive.org/web/20150315093139/http://acm.tju.edu.cn/toj/showp1001.html for instance. Then you can simply change the `1001` in the URL to the problem number, and that should (mostly) work.

**Comment by MegaCha0s** [comment]
Thank You
